mibile.intranet/Controllers/NewsController.cs
using mibile.intranet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mibile.intranet.Controllers
{
    [Authorize(Roles=@"NTDOM\kimep.mobile.news")]
    public class NewsController : Controller
    {
        regofficeEntities db = new regofficeEntities();        
        public ActionResult Index()
        {
            var model = db.mobile_News.OrderByDescending(n => n.CreatedOn);
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Details(int id)
        {
            var model = db.mobile_News.Find(id);
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var model = db.mobile_News.Find(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(mobile_News model)
        {
            if (ModelState.IsValid)
            {
                var news = db.mobile_News.Find(model.ID);

                news.ShortText = model.ShortText;
                news.FullText = model.FullText;
                news.URL = model.URL;
                news.Title = model.Title;
                news.CreatedOn = DateTime.Now;

                db.SaveChanges();

                if (model.Photo != null)
                {
                    byte[] buffer = new byte[model.Photo.ContentLength];
                    model.Photo.InputStream.Read(buffer, 0, model.Photo.ContentLength);
                    db.mobile_News_Image.Add(new mobile_News_Image()
                    {
                        ContentType = model.Photo.ContentType,
                        NewsID = model.ID,
                        Name = model.Photo.FileName,
                        PostedOn = DateTime.Now,
                        Image = buffer
                    });

                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            return View(model);
        }
        public FileResult Photo(int id)
        {
            var photo = db.mobile_News_Image.Find(id);
            return File(photo.Image, photo.ContentType);
        }
        public JsonResult DeletePhoto(int id)
        {
            var photo = db.mobile_News_Image.Find(id);
            var news_id = photo.NewsID;
            db.mobile_News_Image.Remove(photo);
            db.SaveChanges();
            return Json("Success", JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int id)
        {
            var model = db.mobile_News.Find(id);
            if (model != null)
            {
                db.mobile_News.Remove(model);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Create(mobile_News model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedOn = DateTime.Now;
                db.mobile_News.Add(model);
                db.SaveChanges();

                if (model.Photo != null)
                {
                    byte[] buffer = new byte[model.Photo.ContentLength];
                    model.Photo.InputStream.Read(buffer, 0, model.Photo.ContentLength);
                    db.mobile_News_Image.Add(new mobile_News_Image()
                    {
                        ContentType = model.Photo.ContentType,
                        NewsID = model.ID,
                        Name = model.Photo.FileName,
                        PostedOn = DateTime.Now,
                        Image = buffer
                    });

                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

mibile.intranet/Views/News/Create.cshtml
@using mibile.intranet.Models
@model mobile_News

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "News", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortText, new { htmlAttributes = new { @class = "form-control", @rows = "4" } })
                @Html.ValidationMessageFor(model => model.ShortText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullText, new { htmlAttributes = new { @class = "form-control", @rows = "20" } })
                @Html.ValidationMessageFor(model => model.FullText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Photo, new { @class = "form-control", @type = "file" })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mibile.intranet/Views/News/Details.cshtml
@using mibile.intranet.Models
@model mobile_News

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PushID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PushID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @foreach (var photo in Model.mobile_News_Image)
            {
                <img src="@Url.Action("Photo", new { id = photo.ID })" style="max-height: 200px; max-width: 200px;" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

mibile.intranet/Views/News/Edit.cshtml
@using mibile.intranet.Models
@model mobile_News

@{
    ViewBag.Title = "Edit";
}

<h2>
    @ViewBag.Title
</h2>


@using (Html.BeginForm("Edit", "News", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortText, new { htmlAttributes = new { @class = "form-control", @rows = "4" } })
                @Html.ValidationMessageFor(model => model.ShortText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullText, new { htmlAttributes = new { @class = "form-control", @rows = "20" } })
                @Html.ValidationMessageFor(model => model.FullText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Photo, new { @class = "form-control", @type = "file" })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        @foreach (var photo in Model.mobile_News_Image)
        {
            <div class="col-md-3">
                <button type="button" class="close" aria-label="Close" data-id="@photo.ID">
                    <span aria-hidden="true">&times;</span>
                </button>
                <img class="col-md-12" src="@Url.Action("Photo", new { id = photo.ID })" />
            </div>
        }

        <hr />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $("button.close").click(function (event) {
            var btn = $(this);
            var id = btn.data("id");
            $.getJSON("@Url.Action("DeletePhoto", "News")/" + id, function (data) {
                btn.closest("div.col-md-3").remove();
            });
        });
    </script>
}

mibile.intranet/Views/News/Index.cshtml
@using mibile.intranet.Models
@model IEnumerable<mobile_News>

@{
    ViewBag.Title = "News";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>

<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    var photo = item.mobile_News_Image.FirstOrDefault();
    <tr>
        <td>
            @if (photo != null)
            {
                <img src="@Url.Action("Photo", new { id = photo.ID })" style="max-height: 100px; max-width: 100px;" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @onclick = "return confirm('Are you sure want to delete?')" })
        </td>
    </tr>
}
</table>